Backport the docker-wait-ready script from the newer docker cookbook

diff --git a/templates/default/docker.conf.erb b/templates/default/docker.conf.erb
--- a/templates/default/docker.conf.erb
+++ b/templates/default/docker.conf.erb
@@ -40,19 +40,18 @@ script
 	exec "$DOCKER" -d $DOCKER_OPTS
 end script
 
-# Don't emit "started" event until docker.sock is ready.
+# Don't emit "started" event until the docker socket is ready.
 # See https://github.com/docker/docker/issues/6647
 post-start script
-	DOCKER_OPTS=
-	if [ -f /etc/default/$UPSTART_JOB ]; then
-		. /etc/default/$UPSTART_JOB
-	fi
-	if ! printf "%s" "$DOCKER_OPTS" | grep -qE -e '-H|--host'; then
-		while ! [ -e /var/run/docker.sock ]; do
-			initctl status $UPSTART_JOB | grep -q "stop/" && exit 1
-			echo "Waiting for /var/run/docker.sock"
-			sleep 0.1
-		done
-		echo "/var/run/docker.sock is up"
-	fi
+  DOCKER_OPTS=
+  if [ -f /etc/default/$UPSTART_JOB ]; then
+    . /etc/default/$UPSTART_JOB
+  fi
+  <%= @docker_wait_ready %>
+  if [ $? -eq 0 ]; then
+    echo "<%= @docker_socket %> is up"
+  else
+    echo "<%= @docker_socket %> failed to start"
+    exit 1
+  fi
 end script
